{ ... }:
{
  imports = [
    ./alertmanager
    ./aria2
    ./backup
    ./bazarr
    ./blackbox
    ./blocky
    ./dyndns
    ./finance
    ./freshrss
    ./fritzbox
    ./gitea
    ./grafana
    ./hedgedoc
    ./home-automation
    ./homepage
    ./homer
    ./initrd-ssh
    ./jellyfin
    ./jellyseerr
    ./loki
    ./minecraft-server
    ./matrix-bot
    ./mumble-server
    ./navidrome
    ./nextcloud
    ./nginx
    ./node-exporter
    ./octoprint
    ./paperless
    ./passworts
    ./photos
    ./prometheus
    ./promtail
    ./prowlarr
    ./radarr
    ./remote-build
    ./rss-bridge
    ./sonarr
    ./ssh-server
    ./tandoor-recipes
    ./vpn
  ];
}
