{ ... }:
{
  imports = [
    ./alertmanager
    ./aria2
    ./backup
    ./bazarr
    ./blackbox
    ./blocky
    ./dyndns
    ./exportarr
    ./freshrss
    ./gitea
    ./grafana
    ./hedgedoc
    ./home-automation
    ./homepage
    ./homer
    ./initrd-ssh
    ./jellyfin
    ./jellyseerr
    ./loki
    ./minecraft-server
    ./matrix-bot
    ./mumble-server
    ./navidrome
    ./nextcloud
    ./nginx
    ./node-exporter
    ./octoprint
    ./paperless
    ./passworts
    ./photoprism
    ./prometheus
    ./promtail
    ./prowlarr
    ./radarr
    ./rss-bridge
    ./sonarr
    ./ssh-server
    ./tandoor-recipes
  ];
}
